apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-service-deployment
  labels: 
    app: compliance
spec:
  selector:
    matchLabels: 
      app: compliance
  template:
    metadata:
      labels:
        app: compliance
    spec:
      containers:
        - name: compliance-service
          image: localhost:32000/compliance-service:latest
          ports:
            - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata: 
  name: compliance-service-expose
spec:
  type: NodePort
  selector:
    app: compliance
  ports:
    - port: 8092
      targetPort: 8092
      nodePort: 31144
